import { StyleSheet, Platform, Dimensions, StatusBar } from "react-native";

const { width } = Dimensions.get("window");
const CARD_WIDTH = width - 32;

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "#F9FAFB",
    paddingBottom: 100,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
  },
  authContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#F9FAFB",
  },
  authText: {
    fontSize: 18,
    color: "#4B5563",
    marginBottom: 20,
    textAlign: "center",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 40,
    paddingBottom: 20,
    backgroundColor: "#5E72E4",
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 5,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFF",
  },
  headerIcons: {
    flexDirection: "row",
    alignItems: "center",
  },
  section: {
    marginTop: 20,
    marginHorizontal: 16,
    padding: 16,
    backgroundColor: "#FFF",
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#374151",
    marginBottom: 12,
  },
  photoButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  photoButton: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#6B46C1",
    backgroundColor: "transparent",
    marginHorizontal: 4,
  },
  photoButtonActive: {
    backgroundColor: "#6B46C1",
  },
  photoButtonText: {
    marginLeft: 8,
    color: "#6B46C1",
    fontWeight: "600",
  },
  photoButtonTextActive: {
    color: "#FFF",
  },
  previewContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  imagePreviewWrapper: {
    width: "48%",
    position: "relative",
  },
  previewLabel: {
    fontSize: 14,
    color: "#6B46C1",
    fontWeight: "600",
    marginBottom: 8,
  },
  imagePreview: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 8,
    backgroundColor: "#E5E7EB",
  },
  clearButton: {
    position: "absolute",
    top: 24,
    right: 8,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 12,
    width: 24,
    height: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  instructionText: {
    color: "#9CA3AF",
    textAlign: "center",
    marginVertical: 12,
  },
  notesInput: {
    minHeight: 100,
    padding: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 8,
    backgroundColor: "#FFF",
    color: "#374151",
    textAlignVertical: "top",
  },
  submitButton: {
    marginHorizontal: 16,
    marginTop: 20,
    paddingVertical: 16,
    borderRadius: 8,
    backgroundColor: "#6B46C1",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#6B46C1",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  submitButtonDisabled: {
    opacity: 0.6,
  },
  submitButtonText: {
    color: "#FFF",
    fontWeight: "600",
    fontSize: 16,
  },
  emptyState: {
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 40,
  },
  emptyStateText: {
    marginTop: 12,
    color: "#9CA3AF",
    fontSize: 16,
  },
  uploadCard: {
    marginBottom: 20,
    borderRadius: 12,
    backgroundColor: "#FFF",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 3,
    overflow: "hidden",
  },
  uploadHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  uploadDate: {
    color: "#6B7280",
    fontSize: 14,
  },
  comparisonContainer: {
    flexDirection: "row",
    padding: 16,
  },
  comparisonItem: {
    width: "48%",
    marginHorizontal: "1%",
  },
  comparisonLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#6B46C1",
    marginBottom: 8,
  },
  comparisonImage: {
    width: "100%",
    aspectRatio: 4 / 3,
    borderRadius: 8,
    backgroundColor: "#F3F4F6",
  },
  placeholderImage: {
    width: "100%",
    aspectRatio: 4 / 3,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F3F4F6",
    borderRadius: 8,
  },
  placeholderText: {
    marginTop: 8,
    color: "#9CA3AF",
    fontSize: 12,
  },
  actionButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 6,
    backgroundColor: "#EDE9FE",
  },
  actionButtonText: {
    marginLeft: 4,
    color: "#6B46C1",
    fontSize: 12,
    fontWeight: "500",
  },
  deleteButton: {
    backgroundColor: "#FEE2E2",
  },
  deleteButtonText: {
    color: "#DC2626",
  },
  notesContainer: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#F3F4F6",
  },
  notesUserName: {
    fontWeight: "600",
    color: "#374151",
    marginBottom: 4,
  },
  notesText: {
    color: "#4B5563",
    lineHeight: 20,
  },
  modalBackground: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.9)",
    justifyContent: "center",
    alignItems: "center",
  },
  fullscreenImage: {
    width: "100%",
    height: "80%",
  },
  closePreviewButton: {
    position: "absolute",
    top: Platform.OS === "ios" ? 60 : 40,
    right: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    borderRadius: 20,
    padding: 8,
  },
  loginButton: {
    marginTop: 20,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    backgroundColor: "#6B46C1",
  },
  loginButtonText: {
    color: "#FFF",
    fontWeight: "600",
  },
  iconContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
});
